workflow: 
  rules: 
      - if: $CI_COMMIT_BRANCH
image: docker:19.03.11
variables:
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03.11-dind
before_script:
  - apk add bash openssl nodejs npm
  - docker info
test:
  script: 
    - ./test/release_test.sh
doc:
  script:
    - npm install
    - npm run convertDoc
    - rm -fr docs
    - mv documentMD/_user_guide docs
