workflow: 
  rules: 
      - if: $CI_COMMIT_BRANCH
image: docker:19.03.11
variables:
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03.11-dind
before_script:
  - apk add bash openssl nodejs npm git
  - docker info
test:
  script: 
    - ./test/release_test.sh
makedoc:
  script:
    - npm install
    - npm run convertDoc
    - rm -fr docs
    - mv documentMD/_user_guide docs
  artifacts:
    paths:
      - docs/

storedoc:
  stage: "deploy"
  script:
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git config --global core.sshCommand "ssh -oStrictHostKeyChecking=no"
    - git add docs
    - git commit -m "generated html docs from $CI_COMMIT_SHORT_SHA [skip ci]" || echo "No changes, nothing to commit!"
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git push origin HEAD:$CI_COMMIT_REF_NAME # Pushes to the same branch as the trigger
  