repository: taki-036/OPEN-WHEEL
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-polyglot
title: "WHEEL user guide"
subtitle: "Workflow in Hierarchical distributEd parallEL"
strict_front_matter: true


url: "https://taki-036.github.io"
baseurl: "/OPEN-WHEEL"

locate: "ja-JP"
search: true
search_full_content: true
search_provider: "lunr"
lunr:
  search_within_pages: true

include:
  - _pages

atom_feed:
  hide: true

collections:
  reference:
    output: true
    permalink: /:collection/:path
  tutorial:
    output: true
    permalink: /:collection/:path
  how_to_boot:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: reference
    values:
      layout: single
      toc: true
      toc_sticky: true
      sidebar:
        nav: "refs"
  - scope:
      path: ""
      type: tutorial
    values:
      layout: single
      toc: true
      toc_sticky: true
      sidebar:
        nav: "user-docs"
  - scope:
      path: ""
      type: how_to_boot
    values:
      layout: single
      toc: true
      toc_sticky: true

# For jekyll-polyglot
languages: ["ja", "en"]
default_lang: ["en"]
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
lang_from_path: true
langsep: "/"