version: "3"
services:
  service_jekyll:
    image: "jekyll/jekyll:latest"
    environment:
      - JEKYLL_UID=1010
      - JEKYLL_GID=1010
    volumes:
      - .:/srv/jekyll/
    command: >
      bash -c "gem install webrick &&
      gem install jekyll-remote-theme &&
      gem install jekyll-include-cache &&
      gem install jekyll-polyglot &&
      jekyll build"
    tty: true
    stdin_open: true
