volumes:
  work_around:
services:
  service_jekyll:
    image: "jekyll/jekyll:latest"
    environment:
      - JEKYLL_UID=1001
    volumes:
      - .:/srv/jekyll/
      - work_around:/srv/jekyll/_tutorial/3_application_tutorial/4_OpenFOAM_jupyter/sample/OpenFOAM_jupyter.wheel
    command: >
      bash -c "gem install webrick &&
      gem install jekyll-remote-theme &&
      gem install jekyll-include-cache &&
      gem install jekyll-polyglot &&
      jekyll build"
    tty: true
    stdin_open: true
