name: push repo to gitlab for backup
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  backup:
    steps:
      - uses: actions/checkout@v3
      - name: push to gitlab for backup
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          git push https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/aicshud/WHEEL.git HEAD:${BRANCH_NAME}
