name: build and deploy container
on:
  pull_request_target:
    types:
      - closed
jobs:
  build:
    if: github.event.pull_request.merged == true
    env:
      DOCKER_USER_NAME: ${{ vars.DOCKER_USER_NAME }}
      DOCKER_CONTAINER_NAME: ${{ vars.DOCKER_CONTAINER_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t ${DOCKER_USER_NAME}/${DOCKER_CONTAINER_NAME} .
      - run: docker login -u ${DOCKER_USER_NAME} -p ${DOCKER_PASSWORD}
      - run: docker push ${DOCKER_USER_NAME}/${DOCKER_CONTAINER_NAME}
