name: update version on master
on:
  push:
    branches:
      - master
jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "VERSION_NUMBER=$(date '+%Y-%m%d-%H%M%S')-release" >>$GITHUB_ENV
      - run: cat server/app/db/version.json
      - name: update version.json
        uses: jsdaniell/create-json@v1.2.2
        with:
          dir: "server/app/db"
          name: "version.json"
          json: '{"version": "${{ env.VERSION_NUMBER }}" }'
      - run: cat server/app/db/version.json
      - name: commit and push version.json
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config user.name 'version-number-updater[bot]'
          git config user.email 'action@github.com'
          git add server/app/db/version.json
          git commit -m '[skip ci] update version number'
          git push origin HEAD:${GITHUB_REF}
